"""Tests for the order-service data models.

``OrderRequest`` is the validated client input; ``OrderEvent`` is the enriched
record published to Kafka. ``from_request`` is the bridge that stamps the
server-controlled fields (order_id, status, created_at).
"""

from datetime import datetime

import pytest
from pydantic import ValidationError

from app.models import OrderEvent, OrderRequest


def test_valid_request():
    req = OrderRequest(product_id="PROD-001", quantity=5, customer_id="CUST-1")
    assert req.quantity == 5


def test_quantity_below_one_is_rejected():
    with pytest.raises(ValidationError):
        OrderRequest(product_id="PROD-001", quantity=0, customer_id="CUST-1")


def test_missing_field_is_rejected():
    with pytest.raises(ValidationError):
        OrderRequest(product_id="PROD-001", quantity=1)  # no customer_id


def test_from_request_stamps_server_fields():
    req = OrderRequest(product_id="PROD-001", quantity=5, customer_id="CUST-1")
    event = OrderEvent.from_request(req)

    # Copied from the request
    assert event.product_id == "PROD-001"
    assert event.quantity == 5
    assert event.customer_id == "CUST-1"

    # Generated by the server
    assert event.order_id  # non-empty UUID string
    assert event.status == "PENDING"
    assert isinstance(event.created_at, datetime)


def test_each_event_gets_a_unique_order_id():
    req = OrderRequest(product_id="PROD-001", quantity=1, customer_id="CUST-1")
    first = OrderEvent.from_request(req)
    second = OrderEvent.from_request(req)
    assert first.order_id != second.order_id


def test_status_is_locked_to_pending():
    """The Literal["PENDING"] type means a client cannot forge another
    status."""
    with pytest.raises(ValidationError):
        OrderEvent(
            order_id="x",
            product_id="PROD-001",
            quantity=1,
            customer_id="CUST-1",
            status="SHIPPED",
        )
